### ISSUE TITLE
Regenerate source-code with new generator template

### ISSUE THREAD

**Issue by PutraSudaryanto** [ommu/mod-article#1]
#### DESCRIPTION
- enable templateColumns in models
- enable publish/unpublish with trash condition
- enable bootstrap in form
- change $_GET with Yii getParam function
- and others

#### TASK
- [ ] settings
- [ ] categories
- [ ] articles
- [ ] article images
- [ ] article files
- [ ] article tags
- [ ] article views and history view
- [ ] article downloads and history download
- [ ] article likes and history like
